[project]
name = "ticket-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Oran-CK", email = "oran889@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "ollama>=0.6.3",
]

[project.scripts]
ticket-system = "ticket_system:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
